[icons]
icons = "awesome4"

[theme.overrides]
separator = ""
idle_bg = "#1d2021"
info_bg = "#1d2021"
good_bg = "#1d2021"
warning_bg = "#1d2021"
critical_bg = "#1d2021"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2)"

[[block]]
block = "custom"
command = ''' if [ -f "/home/toni/.local/state/keep_on" ]; then echo "on"; fi '''
interval = 5

[[block]]
block = "battery"
device = "BAT0"
format = " $icon $percentage |"
full_format = "|"
empty_format = " $icon $percentage "
not_charging_format = " $icon $percentage "
missing_format = ""
info = 60
good = 95
warning = 30
critical = 15
[[block.click]]
button = "left"
cmd = "gnome-power-statistics"

[block.theme_overrides]
good_bg = "#00000000"
good_fg = "#ebdbb2"
info_bg = "#00000000" 
info_fg = "#ebdbb2"
warning_bg = "#00000000"
warning_fg = "#fabd2f"
critical_bg = "#00000000"
critical_fg = "#fb4934"