# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d47cc50e-70a0-437b-bb7c-5191fb82dadd";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f52b9d4c-26f1-4326-9ffb-7f27dba89b8b".device = "/dev/disk/by-uuid/f52b9d4c-26f1-4326-9ffb-7f27dba89b8b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8CF9-5775";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # This was never found via booting and I couldnt be bothered to find out the problem.
  # Set up swap once I need it, for now I'll just live without
  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
