#!/bin/bash
#
if [ $# -eq 0 ]; then
   echo "Need system name as input"
   exit 1
fi

export SYSTEM_NAME=$1

mkdir -p "$HOME/.config/systemName/"
echo $SYSTEM_NAME > $HOME/.config/systemName/name

cd "$(dirname "$0")"
DOTFILES_ROOT=$(pwd)

for installer in $(find "$DOTFILES_ROOT/" -name "install.sh"); do
    echo $installer
    info "Running '${installer}'"
    bash -c "${installer}" >> ~/installLog
    if [[ $? ]]; then
        success "successfully ran $installer"
    else
        fail "failed to run $installer"
    fi
done
