[general]
separator = " "
default_icon = ""

[options]
no_names = true

[aliases.name]
".*vim.*" = "Vim"
".*nvim.*" = "Vim"

[icons]
"kitty" = ""
TelegramDesktop = ""
firefox = ""
Zathura = ""
default_icon = "💀"
feh = ""
pavucontrol = "🎧"
Zotero = "Z"
pcmanfm = ""
Pcmanfm = ""
Spotify = ""
spotify = ""
KeePassXC = ""
keepassxc = ""
Gimp = ""
gimp = ""
Inkscape = ""
inkscape = ""
Vim = ""
obsidian = ""
