quit_on_last_cancel = true

[[verbs]]
key = "enter"
execution = ":open_stay"

[[verbs]]
key = "ctrl-j"
execution = ":line_down"

[[verbs]]
key = "ctrl-k"
execution = ":line_up"

[[verbs]]
key = "ctrl-h"
execution = ":panel_left"

[[verbs]]
key = "ctrl-l"
execution = ":panel_right"

[[verbs]]
key = "ctrl-u"
execution = ":input_clear"

[[verbs]]
key = "ctrl-w"
execution = ":input_clear"

[[verbs]]
key = "ctrl-o"
execution = ":parent"

[[verbs]]
key = "ctrl-p"
execution = ":print_path"

[[verbs]]
key = "ctrl-p"
execution = ":previous_dir"

[[verbs]]
key = "ctrl-n"
execution = ":next_dir"

[[verbs]]
key = "ctrl-z"
execution = ":toggle_hidden"

[[verbs]]
key = "ctrl-f"
execution = ":toggle_files"