---@type Definition
local global = { -- applies both to main and midi
    command = {
        ["<CM-x>"] = "ShowBindingList",
        ["<ESC>"] = "Reset",
        ["."] = "RepeatLastCommand",
        ["<C-r>"] = "Redo",
        ["u"] = "Undo",
        ["<C-z>"] = "Undo",
        ["<C-s>"] = "SaveProject",

        ["<return>"] = "StartStop",
        ["<SPC>"] = "StartStop",
        ["R"] = "ToggleRecord",

        ["@"] = "PlayMacro",
        [","] = "RecordMacro",

        ["v"] = "SetModeVisualTimeline",
        ["V"] = "SetModeVisualTrack",

        ["<HOME>"] = "ProjectStart",

        ["<DEL>"] = "DeleteItem",


        ["S"] = "SplitItemsUnderMouseCursor",

        ["i"] = { "+insert", {
            ["f"] = "InsertMediaFile",
            ["r"] = "AddSectionTimeSeletion",
            ["p"] = "InsertEnvelopePointAtCursor",
        } },

        ["m"] = { "+mark", {
            ["d"] = "DeleteMarkNearCursor",
            ["a"] = "AddMark",
        } },

        ["g"] = { "track", {
            ["j"] = "GoToJump",
        } },

        ["t"] = { "track", {
            ["a"] = "ArmTracks",
            ["c"] = "ColorTrack",
            ["d"] = "CutTrack",
            ["m"] = "ToggleMute",
            ["n"] = "InsertTrackBelow",
            ["N"] = "InsertTrackFromTemplate",
            ["p"] = "Paste",
            ["P"] = "PasteAbove",
            ["r"] = "RenameTrack",
            ["s"] = "ToggleSolo",
            ["y"] = "CopyTrack",
            ["z"] = "ZoomTrackSelection",
            ["<TAB>"] = "MakeFolder",
            ["<C-h>"] = "NudgeTrackPanLeft",
            ["<C-l>"] = "NudgeTrackPanRight",
            ["<C-H>"] = "NudgeTrackPanLeft10Times",
            ["<C-L>"] = "NudgeTrackPanRight10Times",
        } },
        ["z"] = { "+zoom/move", {
            ["p"] = "ZoomProject",
            ["t"] = "ZoomTrackSelection",
            ["T"] = "ZoomAllTracks",
            ["z"] = "ZoomTimeSelection",
            ["Z"] = "ZoomAllItems",
        } },
        ["s"] = { "+selected items", {
            ["j"] = "NextTake",
            ["k"] = "PrevTake",
            ["g"] = "GlueItemsIgnoringTimeSelection",
            ["m"] = "ToggleMuteItem",
            ["s"] = "ToggleSoloItem",
            ["d"] = "DeleteActiveTake",
            ["c"] = "CropToActiveTake",
            ["h"] = "HealItemsSplits",
            ["x"] = { "+explode takes", {
               ["p"] = "ExplodeTakesInPlace",
               ["o"] = "ExplodeTakesInOrder",
               ["a"] = "ExplodeTakesInAcrossTracks"
            } },
        } },
        [","] = { "+leader commands", {
            ["o"] = { "+options", {
                ["l"] = "ToggleLoop",
                ["m"] = "ToggleMetronome",
                ["p"] = { "+preroll", { 
                    ["p"] = "TogglePlaybackPreroll",
                    ["r"] = "ToggleRecordingPreroll",
                } },
                ["s"] = "ToggleSnap",
                ["t"] = "ToggleStopAtEndOfTimeSelectionIfNoRepeat",
                ["v"] = "ToggleLoopSelectionFollowsTimeSelection",
                ["x"] = "ToggleAutoCrossfade",
                ["z"] = "TogglePlaybackAutoScroll",
                ["r"] = "ToggleLoop",
            } },
            v = { "+view", {
                [","] = "ShowPreferences",
                ['"'] = "ShowSnapshotsWindow",
                ["a"] = "ToggleShowMasterTrack",
                ["A"] = "ShowFloatingMixerMaster",
                ["b"] = "ShowProjectBay",
                ["m"] = "ShowMixer",
                ["n"] = "ShowNavigator",
                ["p"] = "ShowPerformanceMeter",
                ["r"] = "ShowRoutingMatrix",
                ["R"] = "ShowRegionMarkerManager",
                ["s"] = "ShowScaleFinder",
                ["t"] = "ShowTrackManager",
                ["v"] = "ShowVirtualMidiKeyboard",
                ["w"] = "ShowWiringDiagram",
            } },
            ["e"] = { "+envelopes", {
                ["T"] = "ToggleShowAllEnvelope",
                ["a"] = "ToggleArmEnvelopes",
                ["A"] = "ToggleArmAllEnvelopes",
                ["d"] = "ClearEnvelope",
                ["D"] = "ClearAllEnvelope",
                ["t"] = { "+toggle envelope", {
                    ["v"] = "ToggleVolumeEnvelope",
                    ["p"] = "TogglePanEnvelope",
                } },
            } },
            ["f"] = { "+fx", {
                ["a"] = "AddFx",
                ["c"] = "ToggleShowFxChain",
                ["d"] = "CutFxChain",
                ["y"] = "CopyFxChain",
                ["p"] = "PasteFxChain",
                ["b"] = "ToggleFxBypass",
                ["s"] = { "+show", {
                    ["1"] = "ToggleShowFx1",
                    ["2"] = "ToggleShowFx2",
                    ["3"] = "ToggleShowFx3",
                    ["4"] = "ToggleShowFx4",
                    ["5"] = "ToggleShowFx5",
                    ["6"] = "ToggleShowFx6",
                    ["7"] = "ToggleShowFx7",
                    ["8"] = "ToggleShowFx8"
                } },
            } },
            ["p"] = { "+project", {
                [","] = "ShowProjectSettings",
                s = "SaveProject",
                S = "SaveProjectAs",
                ["o"] = "OpenProject",
                ["c"] = "NewProjectTab",
                ["x"] = "CloseProject",
                r = "RenderProject",
                R = "RenderProjectWithLastSetting",
            } },
        } },
    },
}

---@type Definition
local main = {
    ["<DEL>"] = "DeleteItem",

    track_motion = {
        ["G"] = "LastTrack",
        ["gg"] = "FirstTrack",
        ["j"] = "NextTrack",
        ["k"] = "PrevTrack",
    },
    timeline_motion = {
        ["^"] = "ProjectStart",
        ["$"] = "ProjectEnd",
        ["W"] = "NextMeasure",
        ["B"] = "PrevMeasure",
        ["b"] = "PrevBeat",
        ["w"] = "NextBeat",
        ["("] = "TimeSelectionStart",
        [")"] = "TimeSelectionEnd",
    },
    visual_timeline_command = {
        ["c"] = "ClearTimeSelection",
        ["s"] = "SelectItemsAndSplit",
        ["d"] = "CutItems",
        ["y"] = "CopyItems",
        ["g"] = "GlueItems",
        ["z"] = "ZoomTimeSelection",
    },
    command = {
        ["<TAB>"] = "CycleFolderCollapsedState",
        ["d"] = "CutSelectedItems",
        ["y"] = "CopySelectedItems",
        ["p"] = "Paste",
        ["<C-c>"] = "CopySelectedItems",
        ["<C-v>"] = "Paste",
        ["<C-+>"] = "ZoomInVert",
        ["<C-->"] = "ZoomOutVert",
        ["+"] = "ZoomInHoriz",
        ["-"] = "ZoomOutHoriz",
        [";"] = "MoveItemToEditCursor",
        ["%"] = "SplitItemsAtEditCursor",
        ["<C-j>"] = "NudgeTrackVolumeDownBy1",
        ["<C-k>"] = "NudgeTrackVolumeUpBy1",
        ["<C-J>"] = "NudgeTrackVolumeDownBy1Tenth",
        ["<C-K>"] = "NudgeTrackVolumeUpBy1Tenth",
        ["'"] = "MarkedTracks",
    },
}

---@type Definition
local midi = {
    ["<DEL>"] = "DeleteNote",
    timeline_selector = {
        ["s"] = "SelectedNotes",
    },
    timeline_operator = {
        ["d"] = "CutNotes",
        ["y"] = "CopyNotes",
        ["c"] = "FitNotes",
        ["g"] = "JoinNotes",
        ["s"] = "SelectNotes",
        ["z"] = "MidiZoomTimeSelection",
    },
    timeline_motion = {
        ["l"] = "RightMidiGridDivision",
        ["h"] = "LeftMidiGridDivision",
        ["("] = "MidiTimeSelectionStart",
        [")"] = "MidiTimeSelectionEnd",
        ["w"] = "NextNoteStart",
        ["b"] = "PrevNoteStart",
        ["W"] = "NextNoteSamePitchStart",
        ["B"] = "PrevNoteSamePitchStart",
        ["e"] = "EventSelectionEnd",
    },
    command = {
        ["n"] = "AddNextNoteToSelection",
        ["N"] = "AddPrevNoteToSelection",
        ["+"] = "MidiZoomInVert",
        ["-"] = "MidiZoomOutVert",
        ["<C-+>"] = "MidiZoomInHoriz",
        ["<C-->"] = "MidiZoomOutHoriz",
        ["Z"] = "CloseWindow",
        ["a"] = "InsertNote",
        ["p"] = "MidiPaste",
        ["S"] = "UnselectAllEvents",
        ["Y"] = "CopySelectedEvents",
        ["D"] = "CutSelectedEvents",
        ["k"] = "PitchUp",
        ["j"] = "PitchDown",
        ["K"] = "PitchUpOctave",
        ["zp"] = "MidiZoomContent",
        ["J"] = "PitchDownOctave",
        ["<C-b>"] = "PitchUpOctave",
        ["<C-f>"] = "PitchDownOctave",
        ["<C-u>"] = "PitchUp7",
        ["<C-d>"] = "PitchDown7",
        ["V"] = "SelectAllNotesAtPitch",
        ["<M-k>"] = "MoveNoteUpSemitone",
        ["<M-j>"] = "MoveNoteDownSemitone",
        ["<M-K>"] = "MoveNoteUpOctave",
        ["<M-J>"] = "MoveNoteDownOctave",
        ["<M-l>"] = "MoveNoteRight",
        ["<M-h>"] = "MoveNoteLeft",
    },
}

return { ["global"] = global, ["main"] = main, ["midi"] = midi }
