directory: ~/music
library: ~/.local/share/beets/musiclibrary.db
plugins:
    ftintitle
    mpdupdate
    fetchart
    embedart
    chroma
    musicbrainz
musicbrainz:
    host: musicbrainz.org
    ratelimit: 1
    ratelimit_interval: 1.0
    searchlimit: 5
import:
    move: yes
ftintitle:
    drop: yes
language:
    en
original_date:
    yes
