// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1669819782);
user_pref("app.update.lastUpdateTime.background-update-timer", 1669820034);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1669819914);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1672217657);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1669820154);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.dom.window.dump.enabled", false);
user_pref("browser.preferences.animateFadeIn", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.lastAppBuildId", "20221109042202");
user_pref("extensions.lastAppVersion", "6.0.18");
user_pref("extensions.lastPlatformVersion", "60.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.zotero.dataDir", "/home/toni/.local/share/zotero");
user_pref("extensions.zotero.export.lastTranslator", "ca65189f-8815-4afe-8c8b-8c7c15f0edca");
user_pref("extensions.zotero.export.translatorSettings", "{\"exportNotes\":false,\"exportFileData\":false,\"useJournalAbbreviation\":false,\"keepUpdated\":true,\"worker\":true,\"includeAnnotations\":false}");
user_pref("extensions.zotero.fileHandler.pdf", "system");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.lastViewedFolder", "C1");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-collections-pane\":{},\"zotero-tags-splitter\":{},\"zotero-tag-selector-container\":{},\"zotero-collections-splitter\":{},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-pane\":{},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"height\":\"300\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-pane\":{},\"zotero-context-splitter-stacked\":{\"state\":\"open\"},\"zotero-context-pane-inner\":{}}");
user_pref("extensions.zotero.prefVersion", 6);
user_pref("extensions.zotero.purge.tags", true);
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"L1\",\"sessionID\":\"nvQFmNFv\"},{\"id\":\"C1\",\"sessionID\":\"tMDBHDrM\"}]");
user_pref("extensions.zotero.sync.server.username", "tehforsch");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormat", "auth.lower + shorttitle(3,3) + year");
user_pref("extensions.zotero.translators.better-bibtex.platform", "lin");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.skipInstallation", true);
user_pref("extensions.zotfile.dest_dir", "/home/toni/resource/papers");
user_pref("extensions.zotfile.import", false);
user_pref("extensions.zotfile.renameFormat", "%b");
user_pref("extensions.zotfile.source_dir_ff", false);
user_pref("extensions.zotfile.version", "5.1.2");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1669822744);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("places.database.lastMaintenance", 1669822744);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1669822744);
