[posteo]
source = notmuch://~/.local/share/mail
query-map = /home/toni/projects/config/aerc/posteo-query-map
maildir-store = ~/.local/share/mail
maildir-account-path = posteo
multi-file-strategy = act-dir
outgoing = smtps://mail@tonipeter.de@smtp.strato.de:465
outgoing-cred-cmd = cat ~/resource/keys/pw/strato_mail
default = inbox
folders = inbox,archive,sent,drafts,deleted
folders-sort = inbox,archive,sent,drafts,deleted
archive = archive
postpone = drafts
from = Toni Peter <mail@tonipeter.de>
aliases = mail@tonipeter.de
copy-to = sent

[mailbox]
source = notmuch://~/.local/share/mail
query-map = /home/toni/projects/config/aerc/mailbox-query-map
maildir-store = ~/.local/share/mail
maildir-account-path = mailbox
multi-file-strategy = act-dir
outgoing = smtps://toni.peter%40greenbone.net@smtp.mailbox.org:465
outgoing-cred-cmd = /home/toni/projects/config/scripts/getMailboxPw.sh
default = inbox
folders = inbox,archives,sent,drafts,deleted,spam
folders-sort = inbox,archives,sent,drafts,deleted,spam
archive = archive
postpone = drafts
from = Toni Peter <toni.peter@greenbone.net>
aliases = toni.peter@greenbone.net
copy-to = sent

[strato]
source = notmuch://~/.local/share/mail
query-map = /home/toni/projects/config/aerc/strato-query-map
maildir-store = ~/.local/share/mail
maildir-account-path = strato
multi-file-strategy = act-dir
outgoing = smtps://mail%40sokobrane.com@smtp.strato.de:465
outgoing-cred-cmd = cat ~/resource/keys/pw/strato_sokobrane_mail
default = inbox
folders = inbox,archive,sent,drafts,deleted,spam
folders-sort = inbox,archive,sent,drafts,deleted,spam
archive = archive
postpone = drafts
from = Toni Peter <mail@sokobrane.com>
aliases = mail@sokobrane.com
copy-to = sent
