[posteo]
source = maildir://~/.local/share/mail/posteo
outgoing = smtps://mail@tonipeter.de@smtp.strato.de:465
outgoing-cred-cmd = cat ~/resource/keys/pw/strato_mail
default = inbox
folders = inbox,drafts,sent,deleted,archive
folders-sort = inbox,drafts,sent,deleted,archive
archive = archive
postpone = drafts
from = Toni Peter <mail@tonipeter.de>
aliases = tonipeter@posteo.de
copy-to = sent
