[general]
default-save-path = ~/downloads/mail

[ui]
stylesets-dirs = /home/toni/projects/config/aerc/stylesets
styleset-name = toni
sidebar-width = 24
column-separator = " "

[viewer]
alternatives=text/html,text/plain

[compose]
editor = nvim
address-book-cmd = '/home/toni/projects/config/scripts/aerc-address-complete.sh %s'

[ui:account=posteo]
index-columns = flags:3,oldaddr:6,name<22%,subject,date>=
column-oldaddr = {{if match (.Labels | join " ") `old-posteo`}}{{.Style "POSTEO" "old-posteo"}}{{else if match (.Labels | join " ") `old-gmail`}}{{.Style "GMAIL" "old-gmail"}}{{end}}

[filters]
text/plain=cat
text/html=w3m -I UTF-8 -T text/html -cols $(tput cols) -dump

[openers]
application/pgp-signature=true # do nothing
application/pgp-keys=true # do nothing
application/pgp-encrypted=true # do nothing
text/html=firefox {}
text/*=kitty --title aerc-text nvim {}
