sh installPackages.sh
sh installSpotify.sh
sh installVundle.sh
sh installOhMyZsh.sh
sh installSolarizedGnomeTerminal.sh
sh installAck.sh
sh installCommandT.sh
sh installWhenChanged.sh
sh installPip.sh
sh installPythonModules.sh
sh setupSymlinks.sh
