sh ./installPackages.sh
sh ./installAck.sh
sh ./installCommandT.sh
sh ./installGit.sh
sh ./installOhMyZsh.sh
sh ./installPip.sh
sh ./installPythonModules.sh
sh ./installWhenChanged.sh
sh ./installSpotify.sh
sh ./setupSymlinks.sh
sh ./installFasd.sh
sh ./setZshAsDefaultShell.sh
zsh ./installSolarizedGnomeTerminal.sh
