[addressbooks]
[[personal]]
path = ~/.local/share/dav/contacts/personal/contacts

[general]
debug = no
default_action = list
editor = nvim
merge_editor = nvim -d

[contact table]
display = first_name
group_by_addressbook = no
reverse = no
show_nicknames = yes
show_uids = no
sort = last_name

[vcard]
preferred_version = 3.0
search_in_source_files = no
skip_unparsable = no
