#!/bin/sh

set -e

cd $(git rev-parse --show-toplevel)
cd rust

cargo fmt --check
typos
cargo test --all
cargo test --all --features experimental
cargo clippy -- -D warnings 
cargo clippy --features experimental -- -D warnings  

set +e
cd src
rg "dbg\!"
ret=$?
if [[ $ret == 1 ]]; then
    exit 0
else
    echo "dbg statements found"
    exit 1
fi
