#!/bin/sh

set -e

cd $(git rev-parse --show-toplevel)

cargo fmt --check
cargo clippy --all-targets -- -D warnings 
cargo test --all
cargo test --all -- --ignored

set +e
cd src
rg "dbg\!"
ret=$?
if [[ $ret == 1 ]]; then
    exit 0
else
    echo "dbg statements found"
    exit 1
fi
