export XDG_CONFIG_HOME=$(realpath ~/.config)
export XDG_DATA_HOME=$(realpath ~/.local/share)
export XDG_STATE_HOME=$(realpath ~/.local/state)
export XDG_CACHE_HOME=$(realpath ~/.cache)

export ZDOTDIR="$HOME/.config/zsh"
export ZSH_COMPDUMP=$XDG_CACHE_HOME/.zcompdump-$HOST

export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc

export LESSHISTFILE="$XDG_CACHE_HOME"/less/history

export WINEPREFIX="$XDG_DATA_HOME"/wine
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export __GL_SHADER_DISK_CACHE_PATH="$XDG_CACHE_HOME"/nv
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export MYPY_CACHE_DIR="$XDG_CACHE_HOME"/mypy
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

# Setting this to XDG_DATE_HOME is utterly broken in virtually anything except the main rust toolchains where it works - no program respects this shit :(
export CARGO_HOME="$HOME/.cargo"
export RUSTUP_HOME="$HOME/.rustup"

export ANDROID_HOME="$XDG_DATA_HOME"/android