export XDG_CONFIG_HOME=$(realpath ~/.config)
export XDG_DATA_HOME=$(realpath ~/.local/share)
export XDG_STATE_HOME=$(realpath ~/.local/state)
export ZDOTDIR="$HOME/.config/zsh"

export WINEPREFIX="$XDG_DATA_HOME"/wine