(defun python-insert-debug-trace ()
  (interactive)
  (evil-open-above nil)
  (insert "import pdb; pdb.set_trace()")
  (evil-normal-state)
)

(use-package python-black)
(add-hook 'python-mode-hook 'python-black-on-save-mode)
(setq python-black-extra-args '("-l" "160"))
